CREATE TABLE IF NOT EXISTS {}(
tick INTEGER FOREIGN KEY REFERENCES build_order,
game_id INTEGER FOREIGN KEY REFERENCES build_order,
p_Drone INTEGER,
p_Queen INTEGER,
p_Zergling INTEGER,
p_Baneling INTEGER,
p_Roach INTEGER,
p_Ravager INTEGER,
p_Hydralisk INTEGER,
p_Lurker INTEGER,
p_Infestor INTEGER,
p_SwarmHost INTEGER,
p_Ultralisk INTEGER,
p_Overlord INTEGER,
p_Overseer INTEGER,
p_Mutalisk INTEGER,
p_Corruptor INTEGER,
p_Viper INTEGER,
p_BroodLord INTEGER,
p_Hatchery INTEGER,
p_Extractor INTEGER,
p_SpawningPool INTEGER,
p_EvolutionChamber INTEGER,
p_SpineCrawler INTEGER,
p_SporeCrawler INTEGER,
p_RoachWarren INTEGER,
p_BanelingNest INTEGER,
p_Lair INTEGER,
p_HydraliskDen INTEGER,
p_LurkerDen INTEGER,
p_InfestationPit INTEGER,
p_Spire INTEGER,
p_NydusNetwork INTEGER,
p_Hive INTEGER,
p_UltraliskCavern INTEGER,
p_GreaterSpire INTEGER,
p_minerals_available INTEGER,
p_available INTEGER,
e_Probe INTEGER,
e_Zealot INTEGER,
e_Sentry INTEGER,
e_Stalker INTEGER,
e_Adept INTEGER,
e_HighTemplar INTEGER,
e_DarkTemplar INTEGER,
e_Archon INTEGER,
e_Observer INTEGER,
e_WarpPrism INTEGER,
e_Immortal INTEGER,
e_Colossus INTEGER,
e_Disruptor INTEGER,
e_Phoenix INTEGER,
e_VoidRay INTEGER,
e_Oracle INTEGER,
e_Tempest INTEGER,
e_Carrier INTEGER,
e_Mothership INTEGER,
out_Drone NUMERIC(4, 3),
out_Queen NUMERIC(4, 3),
out_Zergling NUMERIC(4, 3),
out_Baneling NUMERIC(4, 3),
out_Roach NUMERIC(4, 3),
out_Ravager NUMERIC(4, 3),
out_Hydralisk NUMERIC(4, 3),
out_Lurker NUMERIC(4, 3),
out_Infestor NUMERIC(4, 3),
out_SwarmHost NUMERIC(4, 3),
out_Ultralisk NUMERIC(4, 3),
out_Overlord NUMERIC(4, 3),
out_Overseer NUMERIC(4, 3),
out_Mutalisk NUMERIC(4, 3),
out_Corruptor NUMERIC(4, 3),
out_Viper NUMERIC(4, 3),
out_BroodLord NUMERIC(4, 3),
PRIMARY KEY (tick, game_id),
);
