CREATE TABLE IF NOT EXISTS {}(
tick INTEGER FOREIGN KEY REFERENCES build_order,
game_id INTEGER FOREIGN KEY REFERENCES build_order,
e_Nexus INTEGER,
e_Pylon INTEGER,
e_Assimilator INTEGER,
e_Gateway INTEGER,
e_Forge INTEGER,
e_PhotonCannon INTEGER,
e_ShieldBattery INTEGER,
e_WarpGate INTEGER,
e_CyberneticsCore INTEGER,
e_TwilightCouncil INTEGER,
e_RoboticsFacility INTEGER,
e_Stargate INTEGER,
e_TemplarArchive INTEGER,
e_DarkShrine INTEGER,
e_RoboticsBay INTEGER,
e_FleetBeacon INTEGER,
out_Probe INTEGER,
out_Zealot INTEGER,
out_Sentry INTEGER,
out_Stalker INTEGER,
out_Adept INTEGER,
out_HighTemplar INTEGER,
out_DarkTemplar INTEGER,
out_Archon INTEGER,
out_Observer INTEGER,
out_WarpPrism INTEGER,
out_Immortal INTEGER,
out_Colossus INTEGER,
out_Disruptor INTEGER,
out_Phoenix INTEGER,
out_VoidRay INTEGER,
out_Oracle INTEGER,
out_Tempest INTEGER,
out_Carrier INTEGER,
out_Mothership INTEGER,
PRIMARY KEY (tick, game_id),
);
