CREATE TABLE IF NOT EXISTS {}(
tick INTEGER FOREIGN KEY REFERENCES build_order,
game_id INTEGER FOREIGN KEY REFERENCES build_order,
e_PlanetaryFortress INTEGER,
e_CommandCenter INTEGER,
e_OrbitalCommand INTEGER,
e_SupplyDepot INTEGER,
e_Refinery INTEGER,
e_Barracks INTEGER,
e_EngineeringBay INTEGER,
e_Bunker INTEGER,
e_MissileTurret INTEGER,
e_SensorTower INTEGER,
e_Factory INTEGER,
e_GhostAcademy INTEGER,
e_Armory INTEGER,
e_Starport INTEGER,
e_FusionCore INTEGER,
e_TechLab INTEGER,
e_Reactor INTEGER,
out_SCV INTEGER,
out_MULE INTEGER,
out_Marine INTEGER,
out_Marauder INTEGER,
out_Reaper INTEGER,
out_Ghost INTEGER,
out_Hellion INTEGER,
out_Hellbat INTEGER,
out_WidowMine INTEGER,
out_SiegeTank INTEGER,
out_Cyclone INTEGER,
out_Thor INTEGER,
out_Viking INTEGER,
out_Medivac INTEGER,
out_Liberator INTEGER,
out_Banshee INTEGER,
out_Raven INTEGER,
out_Battlecruiser INTEGER,
out_Nuke INTEGER,
PRIMARY KEY (tick, game_id),
);
