CREATE TABLE IF NOT EXISTS {}(
tick INTEGER FOREIGN KEY REFERENCES build_order,
game_id INTEGER FOREIGN KEY REFERENCES build_order,
e_Hatchery INTEGER,
e_Extractor INTEGER,
e_SpawningPool INTEGER,
e_EvolutionChamber INTEGER,
e_SpineCrawler INTEGER,
e_SporeCrawler INTEGER,
e_RoachWarren INTEGER,
e_BanelingNest INTEGER,
e_Lair INTEGER,
e_HydraliskDen INTEGER,
e_LurkerDen INTEGER,
e_InfestationPit INTEGER,
e_Spire INTEGER,
e_NydusNetwork INTEGER,
e_Hive INTEGER,
e_UltraliskCavern INTEGER,
e_GreaterSpire INTEGER,
out_Drone NUMERIC(4, 3),
out_Queen NUMERIC(4, 3),
out_Zergling NUMERIC(4, 3),
out_Baneling NUMERIC(4, 3),
out_Roach NUMERIC(4, 3),
out_Ravager NUMERIC(4, 3),
out_Hydralisk NUMERIC(4, 3),
out_Lurker NUMERIC(4, 3),
out_Infestor NUMERIC(4, 3),
out_SwarmHost NUMERIC(4, 3),
out_Ultralisk NUMERIC(4, 3),
out_Overlord NUMERIC(4, 3),
out_Overseer NUMERIC(4, 3),
out_Mutalisk NUMERIC(4, 3),
out_Corruptor NUMERIC(4, 3),
out_Viper NUMERIC(4, 3),
out_BroodLord NUMERIC(4, 3),
PRIMARY KEY (tick, game_id),
);
