CREATE TABLE IF NOT EXISTS {}(
tick INTEGER FOREIGN KEY REFERENCES build_order,
game_id INTEGER FOREIGN KEY REFERENCES build_order,
p_Drone INTEGER,
p_Queen INTEGER,
p_Zergling INTEGER,
p_Baneling INTEGER,
p_Roach INTEGER,
p_Ravager INTEGER,
p_Hydralisk INTEGER,
p_Lurker INTEGER,
p_Infestor INTEGER,
p_SwarmHost INTEGER,
p_Ultralisk INTEGER,
p_Overlord INTEGER,
p_Overseer INTEGER,
p_Mutalisk INTEGER,
p_Corruptor INTEGER,
p_Viper INTEGER,
p_BroodLord INTEGER,
p_Hatchery INTEGER,
p_Extractor INTEGER,
p_SpawningPool INTEGER,
p_EvolutionChamber INTEGER,
p_SpineCrawler INTEGER,
p_SporeCrawler INTEGER,
p_RoachWarren INTEGER,
p_BanelingNest INTEGER,
p_Lair INTEGER,
p_HydraliskDen INTEGER,
p_LurkerDen INTEGER,
p_InfestationPit INTEGER,
p_Spire INTEGER,
p_NydusNetwork INTEGER,
p_Hive INTEGER,
p_UltraliskCavern INTEGER,
p_GreaterSpire INTEGER,
p_minerals_available INTEGER,
p_available INTEGER,
e_Drone INTEGER,
e_Queen INTEGER,
e_Zergling INTEGER,
e_Baneling INTEGER,
e_Roach INTEGER,
e_Ravager INTEGER,
e_Hydralisk INTEGER,
e_Lurker INTEGER,
e_Infestor INTEGER,
e_SwarmHost INTEGER,
e_Ultralisk INTEGER,
e_Overlord INTEGER,
e_Overseer INTEGER,
e_Mutalisk INTEGER,
e_Corruptor INTEGER,
e_Viper INTEGER,
e_BroodLord INTEGER,
out_Drone NUMERIC(4, 3),
out_Queen NUMERIC(4, 3),
out_Zergling NUMERIC(4, 3),
out_Baneling NUMERIC(4, 3),
out_Roach NUMERIC(4, 3),
out_Ravager NUMERIC(4, 3),
out_Hydralisk NUMERIC(4, 3),
out_Lurker NUMERIC(4, 3),
out_Infestor NUMERIC(4, 3),
out_SwarmHost NUMERIC(4, 3),
out_Ultralisk NUMERIC(4, 3),
out_Overlord NUMERIC(4, 3),
out_Overseer NUMERIC(4, 3),
out_Mutalisk NUMERIC(4, 3),
out_Corruptor NUMERIC(4, 3),
out_Viper NUMERIC(4, 3),
out_BroodLord NUMERIC(4, 3),
PRIMARY KEY (tick, game_id),
);
